name: HomeMind
description: ""
ports: []
bricks:
- arduino:web_ui: {}
- arduino:dbstorage_tsstore: {}
- arduino:air_quality_monitoring: {}
- arduino:weather_forecast: {}
- arduino:video_object_detection:
    model: face-detection
- arduino:image_classification:
    model: ei-model-1091645-2
icon: ⚡
